"""
Some constants used in the project
"""

# fmt: off
binding_atoms = {
    'ZN': {
        'CYS': ['SG'],
        'HIS': ['ND1', 'NE2'],
        'ASP': ['OD1', 'OD2'],
        'GLU': ['OE1', 'OE2'],
        'ASN': ['OD1'],
        'GLN': ['OE1'],
        'SER': ['OG'],
        'THR': ['OG1'],
        'TYR': ['OH'],
        'MET': ['SD'],
    },
    'CA': {
        'ASP': ['OD1', 'OD2'],
        'GLU': ['OE1', 'OE2'],
        'ASN': ['OD1'],
        'GLN': ['OE1'],
        'SER': ['OG'],
        'THR': ['OG1'],
        'TYR': ['OH'],
        'LYS': ['NZ'],
        'ARG': ['NH1', 'NH2'],
        'O': ['O'],
    },
    'MG': {
        'ASP': ['OD1', 'OD2'],
        'GLU': ['OE1', 'OE2'],
        'ASN': ['OD1'],
        'GLN': ['OE1'],
        'SER': ['OG'],
        'THR': ['OG1'],
        'TYR': ['OH'],
        'LYS': ['NZ'],
        'ARG': ['NH1', 'NH2'],
        'HIS': ['ND1', 'NE2'],
        'O': ['O'],
    },
    'MN': {
        'ASP': ['OD1', 'OD2'],
        'GLU': ['OE1', 'OE2'],
        'HIS': ['ND1', 'NE2'],
        'ASN': ['OD1'],
        'GLN': ['OE1'],
        'SER': ['OG'],
        'THR': ['OG1'],
        'TYR': ['OH'],
        'CYS': ['SG'],
        'MET': ['SD'],
    },
    'FE': {
        'HIS': ['ND1', 'NE2'],
        'CYS': ['SG'],
        'ASP': ['OD1', 'OD2'],
        'GLU': ['OE1', 'OE2'],
        'TYR': ['OH'],
        'MET': ['SD'],
        'ASN': ['OD1'],
        'GLN': ['OE1'],
        'SER': ['OG'],
        'THR': ['OG1'],
    },
    'CU': {
        'HIS': ['ND1', 'NE2'],
        'CYS': ['SG'],
        'MET': ['SD'],
        'ASP': ['OD1', 'OD2'],
        'GLU': ['OE1', 'OE2'],
        'ASN': ['OD1'],
        'GLN': ['OE1'],
        'SER': ['OG'],
        'THR': ['OG1'],
        'TYR': ['OH'],
    },
    'CO': {
        'HIS': ['ND1', 'NE2'],
        'ASP': ['OD1', 'OD2'],
        'GLU': ['OE1', 'OE2'],
        'CYS': ['SG'],
        'ASN': ['OD1'],
        'GLN': ['OE1'],
        'SER': ['OG'],
        'THR': ['OG1'],
        'TYR': ['OH'],
        'MET': ['SD'],
    },
}

ion_binding_distances = {
    'ZN': {'O': 2.10, 'N': 2.03, 'S': 2.32},
    'CA': {'O': 2.39, 'N': 2.46},
    'MG': {'O': 2.21, 'N': 2.23},
    'MN': {'O': 2.20, 'N': 2.20, 'S': 2.41},
    'FE': {'O': 2.15, 'N': 2.18, 'S': 2.32},
    'CU': {'O': 2.10, 'N': 2.00, 'S': 2.25},
    'CO': {'O': 2.09, 'N': 2.07, 'S': 2.26},
}

ion_coordination_data = {
    'ZN': {
        'min_coordination': 3,
        'max_coordination': 6
    },
    'CA': {
        'min_coordination': 5,
        'max_coordination': 8
    },
    'MG': {
        'min_coordination': 4,
        'max_coordination': 6
    },
    'MN': {
        'min_coordination': 4,
        'max_coordination': 7
    },
    'FE': {
        'min_coordination': 4,
        'max_coordination': 6
    },
    'CU': {
        'min_coordination': 3,
        'max_coordination': 5
    },
    'CO': {
        'min_coordination': 4,
        'max_coordination': 6
    },
}

# Define Van der Waals radii for the elements
# see https://en.wikipedia.org/wiki/Van_der_Waals_radius
vdw_radii = {
    "C": 1.7,
    "N": 1.55,
    "O": 1.52,
    "S": 1.8,
    "ZN": 1.39,
    "CU": 1.40,
    "FE": 1.56,
    "CO": 1.5,  # guess
    "MN": 1.61,
    "MG": 1.73,
    "CA": 2.31,
}

ion_charge = {
    "MN": 2,
    "FE": 3,
    "CU": 2,
    "CO": 2,
    "CA": 2,
    "MG": 2,
    "ZN": 2,
    "NA": 1,
    "CL": -1,
}

"""
substition rules to convert non-standard residue to standard residue
"""
substitutions = {
    "2AS": "ASP",
    "3AH": "HIS",
    "5HP": "GLU",
    "5OW": "LYS",
    "ACL": "ARG",
    "AGM": "ARG",
    "AIB": "ALA",
    "ALM": "ALA",
    "ALO": "THR",
    "ALY": "LYS",
    "ARM": "ARG",
    "ASA": "ASP",
    "ASB": "ASP",
    "ASK": "ASP",
    "ASL": "ASP",
    "ASQ": "ASP",
    "AYA": "ALA",
    "BCS": "CYS",
    "BHD": "ASP",
    "BMT": "THR",
    "BNN": "ALA",
    "BUC": "CYS",
    "BUG": "LEU",
    "C5C": "CYS",
    "C6C": "CYS",
    "CAS": "CYS",
    "CCS": "CYS",
    "CEA": "CYS",
    "CGU": "GLU",
    "CHG": "ALA",
    "CLE": "LEU",
    "CME": "CYS",
    "CSD": "ALA",
    "CSO": "CYS",
    "CSP": "CYS",
    "CSS": "CYS",
    "CSW": "CYS",
    "CSX": "CYS",
    "CXM": "MET",
    "CY1": "CYS",
    "CY3": "CYS",
    "CYG": "CYS",
    "CYM": "CYS",
    "CYQ": "CYS",
    "DAH": "PHE",
    "DAL": "ALA",
    "DAR": "ARG",
    "DAS": "ASP",
    "DCY": "CYS",
    "DGL": "GLU",
    "DGN": "GLN",
    "DHA": "ALA",
    "DHI": "HIS",
    "DIL": "ILE",
    "DIV": "VAL",
    "DLE": "LEU",
    "DLY": "LYS",
    "DNP": "ALA",
    "DPN": "PHE",
    "DPR": "PRO",
    "DSN": "SER",
    "DSP": "ASP",
    "DTH": "THR",
    "DTR": "TRP",
    "DTY": "TYR",
    "DVA": "VAL",
    "EFC": "CYS",
    "FLA": "ALA",
    "FME": "MET",
    "GGL": "GLU",
    "GL3": "GLY",
    "GLZ": "GLY",
    "GMA": "GLU",
    "GSC": "GLY",
    "HAC": "ALA",
    "HAR": "ARG",
    "HIC": "HIS",
    "HIP": "HIS",
    "HMR": "ARG",
    "HPQ": "PHE",
    "HTR": "TRP",
    "HYP": "PRO",
    "IAS": "ASP",
    "IIL": "ILE",
    "IYR": "TYR",
    "KCX": "LYS",
    "LLP": "LYS",
    "LLY": "LYS",
    "LTR": "TRP",
    "LYM": "LYS",
    "LYZ": "LYS",
    "MAA": "ALA",
    "MEN": "ASN",
    "MHS": "HIS",
    "MIS": "SER",
    "MK8": "LEU",
    "MLE": "LEU",
    "MPQ": "GLY",
    "MSA": "GLY",
    "MSE": "MET",
    "MVA": "VAL",
    "NEM": "HIS",
    "NEP": "HIS",
    "NLE": "LEU",
    "NLN": "LEU",
    "NLP": "LEU",
    "NMC": "GLY",
    "OAS": "SER",
    "OCS": "CYS",
    "OMT": "MET",
    "PAQ": "TYR",
    "PCA": "GLU",
    "PEC": "CYS",
    "PHI": "PHE",
    "PHL": "PHE",
    "PR3": "CYS",
    "PRR": "ALA",
    "PTR": "TYR",
    "PYX": "CYS",
    "SAC": "SER",
    "SAR": "GLY",
    "SCH": "CYS",
    "SCS": "CYS",
    "SCY": "CYS",
    "SEL": "SER",
    "SEP": "SER",
    "SET": "SER",
    "SHC": "CYS",
    "SHR": "LYS",
    "SMC": "CYS",
    "SOC": "CYS",
    "STY": "TYR",
    "SVA": "SER",
    "TIH": "ALA",
    "TPL": "TRP",
    "TPO": "THR",
    "TPQ": "ALA",
    "TRG": "LYS",
    "TRO": "TRP",
    "TYB": "TYR",
    "TYI": "TYR",
    "TYQ": "TYR",
    "TYS": "TYR",
    "TYY": "TYR",
}

protein_residues = {
    "ALA",
    "ASN",
    "CYS",
    "GLU",
    "HIS",
    "LEU",
    "MET",
    "PRO",
    "THR",
    "TYR",
    "ARG",
    "ASP",
    "GLN",
    "GLY",
    "ILE",
    "LYS",
    "PHE",
    "SER",
    "TRP",
    "VAL",
}
rnaResidues = {"A", "G", "C", "U", "I"}
dnaResidues = {"DA", "DG", "DC", "DT", "DI"}
nucleotides = rnaResidues | dnaResidues
standard_residues = protein_residues | rnaResidues | dnaResidues
backbone_atoms = {"N", "CA", "C", "O"}
